import Head from "next/head";
import { Inter } from "next/font/google";
import { PageLayout } from "@/components/PageLayout";
import Button from "@/components/Button";
import { useRouter } from "next/router";
import { useState, ChangeEvent } from "react";
import Input from "@/components/Input";
import PDFViewer from "@/components/PDFViewer";
import AnalysisView from "@/components/AnalysisView";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  const [file, setFile] = useState<File | undefined>();

  const handleFileChange = (event: ChangeEvent<HTMLInputElement>) => {
    const selectedFile = event.target.files?.[0];
    setFile(selectedFile);
  };

  var body;
  if (file == undefined) {
    body = (
      <div className="flex justify-center content-center">
        <Input type="file" onChange={handleFileChange} />
      </div>
    );
  } else {
    body = (
      <div className="flex flex-row justify-space items-center">
        <div className="w-1/2">
          <PDFViewer file={file}></PDFViewer>
        </div>
        <div className="w-1/2 ">
          <AnalysisView>
            <p className="font-bold text-4xl text-white mb-6">
              Your Score is <span className="text-green-400">80</span>/100
            </p>
            <p className="text-white max-w-2xl mb-8">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce
              condimentum commodo elit, ac feugiat sapien pulvinar vel. Donec
              vestibulum ex at arcu varius rhoncus. Vestibulum interdum, metus
              vel placerat blandit, metus nulla aliquet risus, vitae venenatis
              sapien ipsum id nunc. Praesent vestibulum velit nisl, quis
              interdum lectus viverra id. Maecenas mattis sapien nec nisi
              suscipit convallis. Curabitur euismod venenatis nunc, nec
              scelerisque justo malesuada ac. Fusce eget fringilla mauris, non
              imperdiet mi. Nam non pulvinar ipsum. Duis sed turpis ut nisl
              iaculis lacinia.
            </p>
            <p className="text-white max-w-2xl">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce
              condimentum commodo elit, ac feugiat sapien pulvinar vel. Donec
              vestibulum ex at arcu varius rhoncus. Vestibulum interdum, metus
              vel placerat blandit, metus nulla aliquet risus, vitae venenatis
              sapien ipsum id nunc. Praesent vestibulum velit nisl, quis
              interdum lectus viverra id. Maecenas mattis sapien nec nisi
              suscipit convallis. Curabitur euismod venenatis nunc, nec
              scelerisque justo malesuada ac. Fusce eget fringilla mauris, non
              imperdiet mi. Nam non pulvinar ipsum. Duis sed turpis ut nisl
              iaculis lacinia.
            </p>
          </AnalysisView>
        </div>
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>CVBoost</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>{body}</PageLayout>
    </>
  );
}
