import Head from "next/head";
import { PageLayout } from "@/components/PageLayout";
import { useEffect, useState } from "react";
import ApiLoader from "../components/ApiLoader";
import useApi from "@/hooks/useApi";
import PreUpload from "@/components/PreUpload";
import PostUpload from "@/components/PostUpload";
import SomethingWentWrong from "@/components/SomethingWentWrong";

export default function Home() {
  const [file, setFile] = useState<File | undefined>();
  const { data, isLoading, error } = useApi(
    "https://func-cvboost.azurewebsites.net/api/resumetrigger",
    file,
    "resume"
  );

  var body;
  if (file == null && isLoading == false) {
    body = <PreUpload setFile={setFile}></PreUpload>;
  } else if (isLoading == true) {
    body = <ApiLoader></ApiLoader>;
  } else if (error) {
    body = <SomethingWentWrong></SomethingWentWrong>;
  } else if (file && isLoading == false && data != undefined) {
    body = <PostUpload file={file} data={data}></PostUpload>;
  }

  return (
    <>
      <Head>
        <title>CVBoost</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>{body}</PageLayout>
    </>
  );
}
