export const loadingSentences: string[] = [
  "Your resume is in good hands. Our team of highly trained hamsters is analyzing it as we speak.",
  "Hang in there, we're scanning your resume for typos and lies..",
  "Your resume is getting the VIP treatment. We've rolled out the red carpet and everything.",
  "We're taking your resume to new heights. We're talking Everest-level heights.",
  "Your resume is getting a first-class analysis. Sit back, relax, and enjoy the ride.",
  "Don't worry, your resume is not lost in cyberspace. We're just giving it a spa treatment.",
  "We're analyzing your resume like a boss. A really cool boss with a fancy tie.",
  "Your resume is being reviewed by our team of ninja robots. They take their job very seriously.",
  "Your resume is undergoing a makeover. It's going to come out looking like a million bucks.",
  "Your resume is getting a check-up. We'll make sure it's healthy and ready to land your dream job.",
  "Our team of unicorns is working hard on your resume analysis. They're magical like that.",
  "Your resume is getting a deep tissue analysis. It's going to feel so good when it's done.",
  "We're not just analyzing your resume, we're giving it a hug. Because everyone needs a hug.",
  "Your resume is on a rocket ship to success. Hang tight, it'll be there soon.",
  "We're analyzing your resume with the precision of a surgeon. Don't worry, no scalpels involved.",
  "Your resume is in good hands. We have the best analysts this side of the galaxy.",
  "We're analyzing your resume so thoroughly, we're practically inside your head. Don't worry, we'll be gentle.",
  "Your resume is being analyzed with the speed of a cheetah. And cheetahs are really fast.",
  "We're analyzing your resume like Sherlock Holmes. We'll find all the clues to get you hired.",
  "We're analyzing your resume so intensely, it's practically sweating. But we won't judge it for being nervous.",
  "Your resume is getting the royal treatment. It's going to be fit for a king or queen.",
  "We're analyzing your resume with the precision of a Swiss watch. And it won't cost you a fortune.",
  "Your resume is getting a makeover. It's going to come out looking like a movie star.",
  "We're analyzing your resume so carefully, we're practically using a microscope. But don't worry, we won't find any bacteria.",
  "Your resume is being analyzed by our team of top-notch analysts. They're like the Avengers, but for resumes.",
  "We're analyzing your resume so thoroughly, it's practically becoming a work of art. But don't worry, we won't frame it and sell it.",
  "Your resume is in good hands. Our analysts are like superheroes, but with less spandex.",
  "We're analyzing your resume with the focus of a zen master. But don't worry, we won't make you meditate.",
  "Your resume is getting the analysis of a lifetime. It's going to be so good, you'll want to frame it.",
  "We're analyzing your resume with the enthusiasm of a puppy. But don't worry, we won't chew on it.",
  "Your resume is in safe hands. We've got our helmets and safety goggles on for this one.",
  "Your achievements are amazing! Well, some of them..",
  "We're almost done, just one more page to go. Or two. Or three. How long is this resume?",
];
